#easy_admin:
#    entities:
#      Teacher:
#        class: App\Entity\Teacher
#        label: 'Maestro'
#        list:
#          title: "Most recent customers"
#          dql_filter: "LOWER(entity.title) LIKE '%%issue%%'"
#        # List the entity class name you want to manage
