twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']    
    globals:
        course_image: '%app.path.course_image%'
        lesson_image: '%app.path.lesson_image%'
        teacher_image: '%app.path.teacher_image%'
