vich_uploader:
    db_driver: orm

    mappings:
        course_images:
            uri_prefix:         '%app.path.course_image%'
            upload_destination: '%kernel.project_dir%/public/%app.path.course_image%'
        lesson_images:
            uri_prefix:         '%app.path.lesson_image%'
            upload_destination: '%kernel.project_dir%/public/%app.path.lesson_image%'
        teacher_images:
            uri_prefix:         '%app.path.teacher_image%'
            upload_destination: '%kernel.project_dir%/public/%app.path.teacher_image%'