version: '3'

services:
  database:
    build:
      context: ./env/database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
#      - ./env/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./env/database/data:/var/lib/mysql

  php-fpm:
    build:
      context: ./env/php
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ./:/var/www
      - ./env/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  nginx:
    build:
      context: ./env/nginx
    volumes:
      - ./:/var/www
      - ./env/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./env/nginx/sites/:/etc/nginx/sites-available
      - ./env/nginx/conf.d/:/etc/nginx/conf.d
      - ./env/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      environment:
        PMA_HOST: database
        PMA_PORT: 3306
      ports:
        - 8080:80
      links:
        - database

